### ISSUE TITLE
Feature: Waterfall Display

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#44]
Use a masonry-style layout to display approved messages in a pseudo-infinite scroll interaction.

Newest messages at the top, displayed left-to-right.

Related to #46

**Comment by csharpfritz** [comment]
This is the lsyout presented on the Index page, but we need to move it to its own page and need new messages to arrive at the top left position

**Comment by degenone** [comment]
I [experimented](https://github.com/degenone/TagzApp/tree/feature_article_ordering) with adding messages in chronological order with JavaScript. End result seems to be correct and it passes the test I made.

Test result: 

![test_data_screenshot](https://github.com/FritzAndFriends/TagzApp/assets/48437506/4beea5e7-3e44-4086-bc2a-db67f25ee9a1)

Running locally:

![real_data_screenshot](https://github.com/FritzAndFriends/TagzApp/assets/48437506/7beab3c3-d2c8-4462-b916-4a506773de63)

*However*, loading the message looks quite janky:

![with_change](https://github.com/FritzAndFriends/TagzApp/assets/48437506/083f9716-528b-4d74-b04f-2d83c872dfde)

Compered to current behavior:

![current](https://github.com/FritzAndFriends/TagzApp/assets/48437506/c2e25ea2-16ee-4717-8299-acd744ab7a3f)

I'm not sure if it could be fixed with a CSS animation or something? Or perhaps another approach is better?

**Comment by csharpfritz** [comment]
Ooh!  Nice idea!Yes, let’s add what you have and we can figure out an animation or some other trigger to load the UI. thank you for researching and the feedbackOn Aug 3, 2023, at 11:01, Tero Kilpeläinen ***@***.***> wrote:﻿Re: [FritzAndFriends/TagzApp] Feature: Waterfall Display (Issue #44)I experimented with adding messages in chronological order with JavaScript. End result seems to be correct and it passes the test I made.Test result:Running locally:However, loading the message looks quite janky:Compered to current behavior:I'm not sure if it could be fixed with a CSS animation or something? Or perhaps another approach is better?—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you authored the thread.Triage notifications on the go with GitHub Mobile for iOS or Android.
